services:
  - type: web
    name: ortenberg-crypto-host
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: API_KEY_LIVE
        value: sk_live_ortenberg_client_001
      - key: API_KEY_TEST
        value: sk_test_ortenberg_client_001
      - key: SPANISH_API_KEY
        value: sk_live_spanish_client_urgent_001
